Fix missing return values
* return false for error conditions
* fixes return-mismatch issues which are fatal by default with gcc-14

oe-service/src/luna_methods.c:812:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:1532:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:1929:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2006:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2057:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2137:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
oe-service/src/luna_methods.c:2217:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]

Signed-off-by: Martin Jansa <martin.jansa@gmail.com>